services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rp-rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default-network

  mysql:
    image: mysql
    container_name: rp-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/usr/db-data
    ports:
      - 3306:3306
    networks:
      - default-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  bff:
    build:
      context: ./bff
      dockerfile: Dockerfile.native
    container_name: rp-bff
    links:
      - rabbitmq
    ports:
     - 8080:8080
    networks:
     - default-network
    restart: on-failure

  message-producer:
    build: ./message-producer
    container_name: rp-message-producer
    links:
      - rabbitmq
    ports:
      - 8081:8081
    networks:
      - default-network
    restart: on-failure

  pessoa-service:
    build: ./pessoa-service
    container_name: rp-pessoa-service
    environment:
      - MYSQL_ADDRESS=172.19.0.1
      - RABBITMQ_ADDRESS=rabbitmq
    links:
      - mysql
      - rabbitmq
    ports:
      - 8082:8082
    networks:
      - default-network
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy

  cargo-service:
    build: ./cargo-service
    container_name: rp-cargo-service
    environment:
      - MYSQL_ADDRESS=172.19.0.1
      - RABBITMQ_ADDRESS=rabbitmq
    links:
      - mysql
      - rabbitmq
    ports:
      - 8083:8083
    networks:
      - default-network
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  rabbitmq_data:
  db-data:

networks:
  default-network:
    driver: bridge
